name: Cross-Compile for Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 cmake ninja-build
      
      - name: Copy SFML
        run: |
          mkdir -p $GITHUB_WORKSPACE/sfml
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/libs
          cp -r $GITHUB_WORKSPACE/libs/sfml/* $GITHUB_WORKSPACE/sfml
      
      - name: Build
        run: |
          mkdir build
          cd build
          x86_64-w64-mingw32-cmake .. -G Ninja -DCMAKE_SYSTEM_NAME=Windows -DSFML_DIR=$GITHUB_WORKSPACE/sfml/SFML-2.6.1/lib/cmake/SFML
          ninja

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatroom-windows
          path: build/*
