name: Cross-Compile for Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 cmake ninja-build

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=Windows \
            -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
            -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
            -DCMAKE_LINKER=x86_64-w64-mingw32-g++ \
            -DSFML_USE_STATIC_STD_LIBS=ON \
            -DSFML_DIR=$GITHUB_WORKSPACE/external/SFML-2.6.1/lib/cmake/SFML
          ninja

      - name: Copy required DLLs
        run: |
          ls /usr/lib/gcc/x86_64-w64-mingw32/
          cp /usr/lib/gcc/x86_64-w64-mingw32/*/libstdc++-6.dll $GITHUB_WORKSPACE/build/
          cp /usr/lib/gcc/x86_64-w64-mingw32/*/libgcc_s_seh-1.dll $GITHUB_WORKSPACE/build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatroom-windows
          path: build/*
